routes/web.php
<?php

use App\Http\Controllers\AboutUsController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SlideController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FooterController;
use App\Http\Controllers\KontenController;
use App\Http\Controllers\SosmedController;
use App\Models\Kategori;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', [HomeController::class, 'index']);


Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('product', ProductController::class);
    Route::resource('kategori', KategoriController::class);
    Route::resource('slide', SlideController::class);
    Route::resource('konten', KontenController::class);
    Route::resource('aboutus', AboutUsController::class);
    Route::resource('contact', ContactController::class);
    Route::resource('sosmed', SosmedController::class);
    Route::resource('footer', FooterController::class);
});
Route::post('/getKabupaten', [ProductController::class, 'getKabupaten'])->name('getKabupaten');

//route contactus
Route::get('/contact-us', [HomeController::class, 'showContactForm'])->name('contact-us');

//route allproduct
Route::get('/allproduct', [HomeController::class, 'showAllProduct'])->name('allproduct');


//route produk
Route::get('/{id}', [HomeController::class, 'produk'])->name('front.produk.index');
Route::get('/detail/{id}', [HomeController::class, 'detail']);

//route produk sesuai wilayah




//route produk sesuai kategori
Route::get('/produk/kategori/{kategoriId}', [HomeController::class, 'produkByKategori'])->name('produk.by.kategori');

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory;

    protected $table = 'contact';

    protected $fillable = [
        'alamat', 'phone', 'email'
    ];

    protected $hidden = [];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use RealRashid\SweetAlert\Facades\Alert;


class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $contact = Contact::all();
        return view('back.contact.index', compact('contact'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $contact = Contact::find($id);

        return view('back.contact.edit', compact('contact'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            'alamat' => 'required',
            'phone' => 'required|numeric|max:9999999999999',
            'email' => 'required|email',
        ]);

        $data = $request->all();

        $contact = Contact::findOrFail($id);
        $contact->update($data);

        Alert::success('Success', 'Data Berhasil Diupdate');
        return redirect()->route('contact.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        // 
    }
}

resources/views/back/contact/edit.blade.php
@extends('layouts.default')

@section('content')
    
<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			
		</div>
	</div>
</div>
<div class="page-inner mt--5">
	<div class="row">
		<div class="col-md-12">
			<div class="card full-height">
				<div class="card-header">
					<div class="card-head-row">
						<div class="card-title">Edit contact</div>
                        <a href="{{ route ('contact.index') }}" class="btn btn-warning ml-auto"> <i class="fa fa-undo"></i> Back</a>
					</div>
				</div>
				<div class="card-body">
                    <form method="POST" action="{{ route('contact.update', $contact->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="alamat">Alamat</label>
                            <input type="text" name="alamat" id="alamat" value="{{ $contact->alamat }}" class="form-control" id="alamat" placeholder="Masukkan Alamat">
                        </div>
                        <div class="form-group">
                            <label for="phone">Phone</label>
                            <input type="number" name="phone" id="phone" value="{{ $contact->phone }}" class="form-control" id="phone" placeholder="Masukkan No Handphone" maxlength="13">
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" name="email" id="email" value="{{ $contact->email }}" class="form-control" id="email" placeholder="Masukkan Alamat email">
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary " type="submit">Save</button>
                        </div>
                    </form>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/back/contact/index.blade.php
@extends('layouts.default')

@section('content')

<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">

        </div>
    </div>
</div>
<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card full-height">
                <div class="card-header">
                    <div class="card-head-row">
                        <div class="card-title">Data contact</div>
                    </div>
                </div>
                <div class="card-body">
                    @if (Session::has('success'))
                    <div class="alert alert-primary">
                        {{ Session('success') }}
                    </div>
                    @endif
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Nomor</th>
                                    <th>Alamat</th>
                                    <th>Phone</th>
                                    <th>Email</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($contact as $key => $row)
                                <tr>
                                    <td>{{ $key + 1}}</td>
                                    <td>{{ $row -> alamat }}</td>
                                    <td>{{ $row -> phone }}</td>
                                    <td>{{ $row -> email }}</td>
                                    <td>
                                        <a href="{{ route ('contact.edit', $row->id) }}" class="btn btn-warning btn-sm"><i class="fas fa-pencil"></i> </a>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="8" class="text-center" >Data Masih Kosong</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection