routes/web.php
<?php

use App\Http\Controllers\AboutUsController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SlideController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FooterController;
use App\Http\Controllers\KontenController;
use App\Http\Controllers\SosmedController;
use App\Models\Kategori;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', [HomeController::class, 'index']);


Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('product', ProductController::class);
    Route::resource('kategori', KategoriController::class);
    Route::resource('slide', SlideController::class);
    Route::resource('konten', KontenController::class);
    Route::resource('aboutus', AboutUsController::class);
    Route::resource('contact', ContactController::class);
    Route::resource('sosmed', SosmedController::class);
    Route::resource('footer', FooterController::class);
});
Route::post('/getKabupaten', [ProductController::class, 'getKabupaten'])->name('getKabupaten');

//route contactus
Route::get('/contact-us', [HomeController::class, 'showContactForm'])->name('contact-us');

//route allproduct
Route::get('/allproduct', [HomeController::class, 'showAllProduct'])->name('allproduct');


//route produk
Route::get('/{id}', [HomeController::class, 'produk'])->name('front.produk.index');
Route::get('/detail/{id}', [HomeController::class, 'detail']);

//route produk sesuai wilayah




//route produk sesuai kategori
Route::get('/produk/kategori/{kategoriId}', [HomeController::class, 'produkByKategori'])->name('produk.by.kategori');

app/Models/Slide.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Slide extends Model
{
    use HasFactory;

    protected $table = 'slide';

    protected $fillable = [
        'judul_slide', 'deskripsi', 'gambar_slide', 'nowa'
    ];

    protected $hidden = [];
}

app/Http/Controllers/SlideController.php
<?php

namespace App\Http\Controllers;

use App\Models\Slide;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use RealRashid\SweetAlert\Facades\Alert;

class SlideController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $slide = Slide::all();

        return view('back.slide.index', compact('slide'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('back.slide.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'judul_slide' => 'required|string|max:255',
            'gambar_slide' => 'nullable|image|mimes:png,jpg,webp,jpeg,gif,bmp',
            'nowa' => ['required', 'numeric', 'regex:/^8/'],
            'deskripsi' => 'required|string',
        ], [
            'judul_slide.required' => 'Judul slide harus diisi.',
            'judul_slide.max' => 'Judul slide tidak boleh lebih dari :max karakter.',
            'gambar_slide.image' => 'File harus berupa gambar.',
            'gambar_slide.mimes' => 'Format gambar tidak valid. Pilih format yang sesuai: png, jpg, webp, jpeg, gif, bmp.',
            'gambar_slide.max' => 'Ukuran gambar tidak boleh lebih dari :max kilobyte.',
            'nowa.required' => 'Nomor WhatsApp harus diisi.',
            'nowa.numeric' => 'Nomor WhatsApp harus berupa angka.',
            'nowa.regex' => 'Nomor WhatsApp harus dimulai dengan angka 8.',
            'deskripsi.required' => 'Deskripsi harus diisi.',
            'deskripsi.string' => 'Deskripsi harus berupa teks.',
        ]);

        $newname = 'slide-' . time() . '.jpg';
        $data = $request->all();
        if ($request->hasFile('gambar_slide')) {
            $data['gambar_slide'] = $request->file('gambar_slide')->storeAs('slide', $newname);
        }

        // Menambahkan prefix "62" ke nomor WhatsApp
        $data['nowa'] = '62' . $data['nowa'];

        Slide::create($data);

        Alert::success('Success', 'Data Berhasil Ditambah');
        return redirect()->route('slide.index');
    }


    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $slide = Slide::find($id);


        return view('back.slide.edit', [
            'slide' => $slide,
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $this->validate($request, [
            'judul_slide' => 'required|string|max:255',
            'gambar_slide' => 'nullable|image|mimes:png,jpg,webp,jpeg,gif,bmp',
            'nowa' => 'required|numeric',
            'deskripsi' => 'required|string',
        ], [
            'judul_slide.required' => 'Judul slide harus diisi.',
            'judul_slide.max' => 'Judul slide tidak boleh lebih dari :max karakter.',
            'gambar_slide.image' => 'File harus berupa gambar.',
            'gambar_slide.mimes' => 'Format gambar tidak valid. Pilih format yang sesuai: png, jpg, webp, jpeg, gif, bmp.',
            'gambar_slide.max' => 'Ukuran gambar tidak boleh lebih dari :max kilobyte.',
            'nowa.required' => 'Nomor WhatsApp harus diisi.',
            'nowa.numeric' => 'Nomor WhatsApp harus berupa angka.',
            'deskripsi.required' => 'Deskripsi harus diisi.',
            'deskripsi.string' => 'Deskripsi harus berupa teks.',
        ]);

        if (empty($request->file('gambar_slide'))) {
            $slide = Slide::find($id);
            $slide->update([
                'judul_slide' => $request->judul_slide,
                'deskripsi' => $request->deskripsi,
                'nowa' => $request->nowa,
            ]);
            Alert::success('Success', 'Data Berhasil Diupdate');
            return redirect()->route('slide.index');
        } else {
            $slide = Slide::find($id);
            Storage::delete($slide->gambar_slide);
            $slide->update([
                'judul_slide' => $request->judul_slide,
                'deskripsi' => $request->deskripsi,
                'nowa' => $request->nowa,
                'gambar_slide' => $request->file('gambar_slide')->store('slide'),
            ]);

            Alert::success('Success', 'Data Berhasil Diupdate');
            return redirect()->route('slide.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $slide = Slide::find($id);

        Storage::delete($slide->gambar_slide);

        $slide->delete();

        Alert::success('Success', 'Data Berhasil Dihapus');
        return redirect()->route('slide.index');
    }
}

resources/views/back/slide/create.blade.php
@extends('layouts.default')

@section('content')

<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">

        </div>
    </div>
</div>
<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card full-height">
                <div class="card-header">
                    <div class="card-head-row">
                        <div class="card-title">Form Slider</div>
                        <a href="{{ route ('slide.index') }}" class="btn btn-warning ml-auto">Back</a>
                    </div>
                </div>
                <div class="card-body">
                    @if ($errors->any())
                    <div class="alert alert-warning">
                        @foreach ($errors->all() as $error)
                        <div>{{ $error }}</div>
                        @endforeach
                    </div>
                    @endif
                    <form method="POST" action="{{ route('slide.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="judul_slide">Judul Slider</label>
                            <input type="text" name="judul_slide" class="form-control" id="judul_slide" placeholder="Masukkan Judul Slider">
                        </div>
                        <div class="form-group">
                            <label for="deskripsi">Deskripsi</label>
                            <textarea name="deskripsi" id="editor" cols="30" rows="10"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="nowa">Nomor WhatsApp</label>
                            <input type="number" id="nowa" name="nowa" class="form-control" placeholder="Masukkan Nomor Dimulai dari 8 Slider">
                        </div>
                        <div class="form-group">
                            <label for="gambar">Gambar </label>
                            <input type="file" name="gambar_slide" id="gambar" class="form-control">
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary " type="submit">Save</button>
                            <button class="btn btn-danger " type="reset">Reset</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.ckeditor.com/4.22.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('editor');
</script>

@endsection

resources/views/back/slide/edit.blade.php
@extends('layouts.default')

@section('content')

<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">

        </div>
    </div>
</div>
<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card full-height">
                <div class="card-header">
                    <div class="card-head-row">
                        <div class="card-title">Edit Slider {{ $slide->judul_slide }}</div>
                        <a href="{{ route ('slide.index') }}" class="btn btn-warning ml-auto">Back</a>
                    </div>
                </div>
                <div class="card-body">
                    <form method="post" action="{{ route('slide.update',$slide->id) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="judul_slide">Judul Slider</label>
                            <input type="text" name="judul_slide" class="form-control" id="judul_slide" value="{{ $slide->judul_slide }}">
                        </div>
                        <div class="form-group">
                            <label for="deskripsi">Deskripsi</label>
                            <div class="form-group">
                                <label for="deskripsi">Deskripsi</label>
                                <textarea name="deskripsi" id="editor" cols="30" rows="10">{{ $slide->deskripsi }}"</textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="nowa">Nomor WhatsApp</label>
                            <input type="text" name="nowa" class="form-control" id="nowa" value="{{ $slide->nowa }}">
                        </div>
                        <div class="form-group">
                            <label for="gambar">Gambar Slider </label>
                            <input type="file" name="gambar_slide" class="form-control">
                            <br>
                            <label for="gambar">Gambar Saat ini </label> <br>
                            <img src="{{ asset('uploads/'. $slide->gambar_slide) }}" alt="" width="150">
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary " type="submit">Save</button>
                            <button class="btn btn-danger " type="reset">Reset</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.ckeditor.com/4.22.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('editor');
</script>
@endsection

resources/views/back/slide/index.blade.php
@extends('layouts.default')

@section('content')

<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">

        </div>
    </div>
</div>
<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card full-height">
                <div class="card-header">
                    <div class="card-head-row">
                        <div class="card-title">Data Slider</div>
                        <a href="{{ route ('slide.create') }}" class="btn btn-primary ml-auto"> <i class="fas fa-plus"></i> Tambah Slider</a>
                    </div>
                </div>
                <div class="card-body">
                    @if (Session::has('success'))
                    <div class="alert alert-primary">
                        {{ Session('success') }}
                    </div>
                    @endif
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Nomor</th>
                                    <th>Judul Slide</th>
                                    <th>Deskripsi</th>
                                    <th>No Wa</th>
                                    <th>Gambar</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($slide as $key => $row)
                                <tr>
                                    <td>{{ $key + 1 }}</td>
                                    <td>{{ $row -> judul_slide }}</td>
                                    <td>{!! $row -> deskripsi !!}</td>
                                    <td>{{ $row -> nowa }}</td>
                                    <td> <img src="{{ asset('uploads/'. $row->gambar_slide) }}" width="150" height="100"></td>
                                    <td>
                                        <a href="{{ route ('slide.edit', $row->id) }}" class="btn btn-warning btn-sm mb-2"><i class="fas fa-pencil"></i></a>

                                        <form action="{{ route ('slide.destroy', $row->id) }}" method="POST" class="d-inline">
                                            @csrf
                                            @method('delete')
                                            <button class="btn btn-danger btn-sm mb-2">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="8" class="text-center">Data Masih Kosong</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection