routes/web.php
<?php

use App\Http\Controllers\AboutUsController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SlideController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FooterController;
use App\Http\Controllers\KontenController;
use App\Http\Controllers\SosmedController;
use App\Models\Kategori;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', [HomeController::class, 'index']);


Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('product', ProductController::class);
    Route::resource('kategori', KategoriController::class);
    Route::resource('slide', SlideController::class);
    Route::resource('konten', KontenController::class);
    Route::resource('aboutus', AboutUsController::class);
    Route::resource('contact', ContactController::class);
    Route::resource('sosmed', SosmedController::class);
    Route::resource('footer', FooterController::class);
});
Route::post('/getKabupaten', [ProductController::class, 'getKabupaten'])->name('getKabupaten');

//route contactus
Route::get('/contact-us', [HomeController::class, 'showContactForm'])->name('contact-us');

//route allproduct
Route::get('/allproduct', [HomeController::class, 'showAllProduct'])->name('allproduct');


//route produk
Route::get('/{id}', [HomeController::class, 'produk'])->name('front.produk.index');
Route::get('/detail/{id}', [HomeController::class, 'detail']);

//route produk sesuai wilayah




//route produk sesuai kategori
Route::get('/produk/kategori/{kategoriId}', [HomeController::class, 'produkByKategori'])->name('produk.by.kategori');

app/Models/Sosmed.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sosmed extends Model
{
    use HasFactory;

    protected $table = 'sosmed';

    protected $fillable = [
        'nama_website', 'whatsapp', 'email_sales'
    ];

    protected $hidden = [];
}

app/Http/Controllers/SosmedController.php
<?php

namespace App\Http\Controllers;

use App\Models\Sosmed;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;


class SosmedController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $sosmed = Sosmed::all();
        return view('back.sosmed.index', compact('sosmed'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        // return view('back.sosmed.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        // $this->validate($request, [
        //     'nama_website' => 'required',
        //     'whatsapp' => 'required',
        //     'email_sales' => 'required',
        // ]);

        // $sosmed = Sosmed::create([
        //     'nama_website' => $request->nama_website,
        //     'whatsapp' => $request->whatsapp,
        //     'email_sales' => $request->email_sales,
        // ]);

        // Alert::success('Success', 'Data Berhasil Disimpan');
        // return redirect()->route('sosmed.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $sosmed = Sosmed::find($id);

        return view('back.sosmed.edit', compact('sosmed'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            'nama_website' => 'required',
            'whatsapp' => 'required|numeric|max:9999999999999',
            'email_sales' => 'required|email',
        ]);

        $data = $request->all();

        $sosmed = Sosmed::findOrFail($id);
        $sosmed->update($data);

        Alert::success('Success', 'Data Berhasil Diupdate');
        return redirect()->route('sosmed.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        // $sosmed = Sosmed::find($id);

        // $sosmed->delete();

        // Alert::success('Success', 'Data Berhasil Dihapus');
        // return redirect()->route('sosmed.index');
    }
}

resources/views/back/sosmed/edit.blade.php
@extends('layouts.default')

@section('content')
    
<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			
		</div>
	</div>
</div>
<div class="page-inner mt--5">
	<div class="row">
		<div class="col-md-12">
			<div class="card full-height">
				<div class="card-header">
					<div class="card-head-row">
						<div class="card-title">Edit sosmed</div>
                        <a href="{{ route ('sosmed.index') }}" class="btn btn-warning ml-auto"> <i class="fa fa-undo"></i> Back</a>
					</div>
				</div>
				<div class="card-body">
                    <form method="POST" action="{{ route('sosmed.update', $sosmed->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="nama_website">Nama Website</label>
                            <input type="text" name="nama_website" id="nama_website" value="{{ $sosmed->nama_website }}" class="form-control" id="text" placeholder="Masukkan Nama Website">
                        </div>
                        <div class="form-group">
                            <label for="whatsapp">whatsapp</label>
                            <input type="number" name="whatsapp" id="whatsapp" value="{{ $sosmed->whatsapp }}" class="form-control" id="text" placeholder="Masukkan Nomor WhatsApp" maxlength="13">
                        </div>
                        <div class="form-group">
                            <label for="email_sales">Email Sales</label>
                            <input type="email" name="email_sales" id="email_sales" value="{{ $sosmed->email_sales }}" class="form-control" id="text" placeholder="Masukkan Nama email_sales">
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary " type="submit">Save</button>
                        </div>
                    </form>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/back/sosmed/index.blade.php
@extends('layouts.default')

@section('content')

<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">

        </div>
    </div>
</div>
<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card full-height">
                <div class="card-header">
                    <div class="card-head-row">
                        <div class="card-title">Data Sosmed</div>
                    </div>
                </div>
                <div class="card-body">
                    @if (Session::has('success'))
                    <div class="alert alert-primary">
                        {{ Session('success') }}
                    </div>
                    @endif
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Nomor</th>
                                    <th>Nama Website</th>
                                    <th>WhatsApp</th>
                                    <th>Email Sales</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($sosmed as $key => $row)
                                <tr>
                                    <td>{{ $key + 1}}</td>
                                    <td>{{ $row -> nama_website }}</td>
                                    <td>{{ $row -> whatsapp }}</td>
                                    <td>{{ $row -> email_sales }}</td>
                                    <td>
                                        <a href="{{ route ('sosmed.edit', $row->id) }}" class="btn btn-warning btn-sm"><i class="fas fa-pencil"></i> </a>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="8" class="text-center" >Data Masih Kosong</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection