routes/web.php
<?php

use App\Http\Controllers\AboutUsController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SlideController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\FooterController;
use App\Http\Controllers\KontenController;
use App\Http\Controllers\SosmedController;
use App\Models\Kategori;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/', [HomeController::class, 'index']);


Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('product', ProductController::class);
    Route::resource('kategori', KategoriController::class);
    Route::resource('slide', SlideController::class);
    Route::resource('konten', KontenController::class);
    Route::resource('aboutus', AboutUsController::class);
    Route::resource('contact', ContactController::class);
    Route::resource('sosmed', SosmedController::class);
    Route::resource('footer', FooterController::class);
});
Route::post('/getKabupaten', [ProductController::class, 'getKabupaten'])->name('getKabupaten');

//route contactus
Route::get('/contact-us', [HomeController::class, 'showContactForm'])->name('contact-us');

//route allproduct
Route::get('/allproduct', [HomeController::class, 'showAllProduct'])->name('allproduct');


//route produk
Route::get('/{id}', [HomeController::class, 'produk'])->name('front.produk.index');
Route::get('/detail/{id}', [HomeController::class, 'detail']);

//route produk sesuai wilayah




//route produk sesuai kategori
Route::get('/produk/kategori/{kategoriId}', [HomeController::class, 'produkByKategori'])->name('produk.by.kategori');

resources/views/includes/footer.blade.php
<footer class="footer" data-background-color="dark2">
        <div class="copyright ml-auto" style="color: white">
            2023, made with <i class="fa fa-heart heart text-danger"></i> by <a style="color: white" href="/dashboard">Smart Florist</a>
        </div>				
    </div>
</footer>

resources/views/includes/header.blade.php
<div class="main-header">
    <!-- Logo Header -->
    <div class="logo-header">
        <a href="/" class="logo">
            <img src="{{ asset('back/img/logo.png') }}" height="50" alt="navbar brand" class="navbar-brand">
        </a>
        <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">
                <i class="icon-menu"></i>
            </span>
        </button>
        <button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
        <div class="nav-toggle">
            <button class="btn btn-toggle toggle-sidebar">
                <i class="icon-menu"></i>
            </button>
        </div>
    </div>
    <!-- End Logo Header -->

    <!-- Navbar Header -->
    <nav class="navbar navbar-header navbar-expand-lg" >
				
        <div class="container-fluid">
            <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
                <li class="nav-item toggle-nav-search hidden-caret">
                    <a class="nav-link" data-toggle="collapse" href="#search-nav" role="button" aria-expanded="false" aria-controls="search-nav">
                        <i class="fa fa-search"></i>
                    </a>
                </li>
                    
                <li class="nav-item dropdown hidden-caret submenu">
                    <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
                        <div class="avatar-sm">
                            <img src="{{ asset('back/img/profile.png') }}" alt="..." class="avatar-img rounded-circle">
                        </div>
                    </a>
                    <ul class="dropdown-menu dropdown-user animated fadeIn">
                        <div class="scroll-wrapper dropdown-user-scroll scrollbar-outer" style="position: relative;"><div class="dropdown-user-scroll scrollbar-outer scroll-content" style="height: 274.138px; margin-bottom: 0px; margin-right: 0px; max-height: none;">
                            <li>
                                <div class="user-box">
                                    <div class="avatar-lg"><img src="{{ asset('back/img/profile.png') }}" alt="image profile" class="avatar-img rounded"></div>
                                    <div class="u-text">
                                        <h6>{{ Auth::user()->name }}</h6>
                                        <p class="text-muted">{{ Auth::user()->email }}</p>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">Logout</a>
                            </li>
                        </div><div class="scroll-element scroll-x"><div class="scroll-element_outer"><div class="scroll-element_size"></div><div class="scroll-element_track"></div><div class="scroll-bar ui-draggable ui-draggable-handle" style="width: 100px;"></div></div></div><div class="scroll-element scroll-y"><div class="scroll-element_outer"><div class="scroll-element_size"></div><div class="scroll-element_track"></div><div class="scroll-bar ui-draggable ui-draggable-handle" style="height: 100px;"></div></div></div></div>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <!-- End Navbar -->
</div>

resources/views/includes/js.blade.php
<!--   Core JS Files   -->
<script src="{{ asset('back/js/core/jquery.3.2.1.min.js') }}"></script>
<script src="{{ asset('back/js/core/popper.min.js') }}"></script>
<script src="{{ asset('back/js/core/bootstrap.min.js') }}"></script>

<!-- jQuery UI -->
<script src="{{ asset('back/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js') }}"></script>
<script src="{{ asset('back/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js') }}"></script>

<!-- jQuery Scrollbar -->
<script src="{{ asset('back/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js') }}"></script>


<!-- Chart JS -->
<script src="{{ asset('back/js/plugin/chart.js/chart.min.js') }}"></script>

<!-- jQuery Sparkline -->
<script src="{{ asset('back/js/plugin/jquery.sparkline/jquery.sparkline.min.js') }}"></script>

<!-- Chart Circle -->
<script src="{{ asset('back/js/plugin/chart-circle/circles.min.js') }}"></script>

<!-- Datatables -->
<script src="{{ asset('back/js/plugin/datatables/datatables.min.js') }}"></script>
<script>
    $(function () {
    $("#example1").DataTable();
    });
</script>

<!-- Bootstrap Notify -->
<script src="{{ asset('back/js/plugin/bootstrap-notify/bootstrap-notify.min.js') }}"></script>

<!-- Sweet Alert -->
<script src="{{ asset('back/js/plugin/sweetalert/sweetalert.min.js') }}"></script>

<!-- Atlantis JS -->
<script src="{{ asset('back/js/atlantis.min.js') }}"></script>

<script>
    $(function() {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('#provinces').on('change', function() {
            let id_provinsi = $('#provinces').val();

            $.ajax({
                type: 'POST',
                url: "{{ route('getKabupaten') }}",
                data: {
                    id_provinsi: id_provinsi
                },
                cache: false,

                success: function(msg) {
                    $('#kabupaten').html(msg);
                },
                error: function(data) {
                    console.log('error:', data)
                },
            })
        });
    });
</script>

resources/views/includes/sidebar.blade.php
<div class="sidebar sidebar-style-2" data-background-color="dark">
    <div class="sidebar-wrapper scrollbar scrollbar-inner">
        <div class="sidebar-content">
            <div class="user">
                <div class="avatar-sm float-left mr-2">
                    <img src="{{ asset('back/img/profile.png') }}" alt="..." class="avatar-img rounded-circle">
                </div>
                <div class="info">
                    <a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
                        <span>
                            Smart-Florist
                            <span class="user-level">{{ Auth::user()->name }}</span>
                        </span>
                    </a>
                    <div class="clearfix"></div>
                </div>
            </div>
            <ul class="nav nav-primary">
                <li class="nav-item active">
                    <a href="/dashboard">
                        <i class="fas fa-home"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-section">
                    <span class="sidebar-mini-icon">
                        <i class="fa fa-ellipsis-h"></i>
                    </span>
                    <h4 class="text-section">Manajement Data</h4>
                </li>
                <li class="nav-item">
                    <a href="{{ route('product.index') }}">
                        <i class="fas fa-cube"></i>
                        <p>Data Produk</p>
                        <span class="badge badge-success"></span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('kategori.index') }}">
                        <i class="fas fa-cubes"></i>
                        <p>Data Kategori</p>
                        <span class="badge badge-success"></span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('slide.index') }}">
                        <i class="far fa-images"></i>
                        <p>Data Slider</p>
                        <span class="badge badge-success"></span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('konten.index') }}">
                        <i class="fab fa-adversal"></i>
                        <p>Data Konten</p>
                        <span class="badge badge-success"></span>
                    </a>
                </li>

                <li class="nav-item">
                    <a data-toggle="collapse" href="#sidebarLayouts">
                        <i class="fas fa-th-list"></i>
                        <p>Data Lainnya</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="sidebarLayouts">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="{{ route('aboutus.index') }}">
                                    <span class="sub-item">Data About Us</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{ route('contact.index') }}">
                                    <span class="sub-item">Data Contact</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{ route('sosmed.index') }}">
                                    <span class="sub-item">Data Sosmed</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{ route('footer.index') }}">
                                    <span class="sub-item">Data Footer</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                        <i class="fas fa-undo"></i>
                        <p>{{ __('Logout') }}</p>
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>
            </ul>
        </div>
    </div>
</div>